version: "3"

services:
  frontend:
    build: ./frontend/
    restart: unless-stopped
    ports:
      - "8080:3000"
  backend:
    build: ./backend/
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - BACKEND_CORS_ORIGINS=http://localhost:8080
    volumes:
      - ./database:/app/database/

networks:
  default:
    name: developer-notifier
    driver: bridge
