"""inital

Revision ID: 3b4baaf4d0c1
Revises: 
Create Date: 2024-10-05 00:18:57.039404

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3b4baaf4d0c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_pull_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('pull_request', sa.Integer(), nullable=False),
    sa.Column('repository', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_assigned', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_pull_requests_pull_request'), 'github_pull_requests', ['pull_request'], unique=True)
    op.create_index(op.f('ix_github_pull_requests_status'), 'github_pull_requests', ['status'], unique=False)
    op.create_index(op.f('ix_github_pull_requests_title'), 'github_pull_requests', ['title'], unique=False)
    op.create_table('jira_issues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('issue', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jira_issues_issue'), 'jira_issues', ['issue'], unique=True)
    op.create_index(op.f('ix_jira_issues_status'), 'jira_issues', ['status'], unique=False)
    op.create_index(op.f('ix_jira_issues_title'), 'jira_issues', ['title'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jira_api_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jira_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jira_api_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('github_access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('github_org', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('github_user', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('github_api_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_jira_api_email'), 'settings', ['jira_api_email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_jira_api_email'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_jira_issues_title'), table_name='jira_issues')
    op.drop_index(op.f('ix_jira_issues_status'), table_name='jira_issues')
    op.drop_index(op.f('ix_jira_issues_issue'), table_name='jira_issues')
    op.drop_table('jira_issues')
    op.drop_index(op.f('ix_github_pull_requests_title'), table_name='github_pull_requests')
    op.drop_index(op.f('ix_github_pull_requests_status'), table_name='github_pull_requests')
    op.drop_index(op.f('ix_github_pull_requests_pull_request'), table_name='github_pull_requests')
    op.drop_table('github_pull_requests')
    # ### end Alembic commands ###
